export const newNames = async ({ oldName }) => {
  switch (oldName) {
    case "nidoran-m":
      return "nidoran";
    case "nidoran-f":
      return "nidoran";
    case "wormadam-plant":
      return "wormadam";
    case "wormadam-sandy":
      return "wormadam";
    case "wormadam-trash":
      return "wormadam";
    case "giratina-altered":
      return "giratina";
    case "giratina-origin":
      return "giratina";
    case "shaymin-land":
      return "shaymin";
    case "shaymin-sky":
      return "shaymin";
    case "basculin-red-striped":
      return "basculin";
    case "basculin-blue-striped":
      return "basculin";
    case "darmanitan-standard":
      return "darmanitan";
    case "darmanitan-zen":
      return "darmanitan";
    case "tornadus-incarnate":
      return "tornadus";
    case "tornadus-therian":
      return "tornadus";
    case "thundurus-incarnate":
      return "thundurus";
    case "thundurus-therian":
      return "thundurus";
    case "landorus-incarnate":
      return "landorus";
    case "landorus-therian":
      return "landorus";
    case "keldeo-ordinary":
      return "keldeo";
    case "keldeo-resolute":
      return "keldeo";
    case "meloetta-aria":
      return "meloetta";
    case "meloetta-pirouette":
      return "meloetta";
    case "meowstic-male":
      return "meowstic";
    case "meowstic-female":
      return "meowstic";
    case "aegislash-shield":
      return "aegislash";
    case "aegislash-blade":
      return "aegislash";
    case "pumpkaboo-average":
      return "pumpkaboo";
    case "pumpkaboo-small":
      return "pumpkaboo";
    case "pumpkaboo-large":
      return "pumpkaboo";
    case "pumpkaboo-super":
      return "pumpkaboo";
    case "gourgeist-average":
      return "gourgeist";
    case "gourgeist-small":
      return "gourgeist";
    case "gourgeist-large":
      return "gourgeist";
    case "gourgeist-super":
      return "gourgeist";
    case "zygarde-50":
      return "zygarde";
    case "zygarde-10":
      return "zygarde";
    case "zygarde-complete":
      return "zygarde";
    case "oricorio-baile":
      return "oricorio";
    case "oricorio-pom-pom":
      return "oricorio";
    case "oricorio-pau":
      return "oricorio";
    case "oricorio-sensu":
      return "oricorio";
    case "lycanroc-midday":
      return "lycanroc";
    case "lycanroc-midnight":
      return "lycanroc";
    case "lycanroc-dusk":
      return "lycanroc";
    case "wishiwashi-solo":
      return "wishiwashi";
    case "wishiwashi-school":
      return "wishiwashi";
    case "minior-red-meteor":
      return "minior";
    case "minior-orange-meteor":
      return "minior";
    case "minior-yellow-meteor":
      return "minior";
    case "minior-green-meteor":
      return "minior";
    case "minior-blue-meteor":
      return "minior";
    case "minior-indigo-meteor":
      return "minior";
    case "minior-violet-meteor":
      return "minior";
    case "minior-red":
      return "minior";
    case "minior-orange":
      return "minior";
    case "minior-yellow":
      return "minior";
    case "minior-green":
      return "minior";
    case "minior-blue":
      return "minior";
    case "minior-indigo":
      return "minior";
    case "minior-violet":
      return "minior";
    case "mimikyu-disguised":
      return "mimikyu";
    case "mimikyu-busted":
      return "mimikyu";
    case "toxtricity-amped":
      return "toxtricity";
    case "toxtricity-low-key":
      return "toxtricity";
    case "eiscue-ice":
      return "eiscue";
    case "eiscue-noice":
      return "eiscue";
    case "morpeko-full-belly":
      return "morpeko";
    case "morpeko-hangry":
      return "morpeko";
    case "urshifu-single-strike":
      return "urshifu";
    case "urshifu-rapid-strike":
      return "urshifu";
    default:
      return oldName;
  }
};
